### ISSUE TITLE
Help with 2 temperature outputs

### ISSUE THREAD

**Issue by chadhutchins182** [mlucool/temper-usb#1]
Hello!

I have this version of temperUSB: [https://www.amazon.com/gp/product/B009YRP906/ref=oh_aui_detailpage_o08_s00?ie=UTF8&psc=1](url) which should produce 1 temperature. However when I run my nodejs code I see 2 data array outputs.

```shell
pi@ns1:~/rack-temp/rack-temp $ sudo node index.js
TempUSB
len: 1
{ data: { '0': 89.6, '1': 213.2375 }, date: 1525741434711 }
pi@ns1:~/rack-temp/rack-temp $ lsusb
Bus 001 Device 007: ID 0c45:7401 Microdia TEMPer Temperature Sensor
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

```javascript
nodejs source
var tempusb = require("temper-usb")

console.log("TempUSB");
var devices = tempusb.getTemperDevices();
console.log("len: "+devices.length);
devices.forEach((td) => td.getTemperature(format="f").then(console.log).catch(console.err));
```

Why am I seeing 2 data array entries? Any help would be greatly appreciated!

**Comment by mlucool** [comment]
I had actually had that one and returned it once. I don't recall why I didn't like that model, but I ended up with the one listed in the readme.

Anyway, that being said:
I hardcoded [this to two sensors](https://github.com/mlucool/temper-usb/blob/master/src/temper.js#L138) for a reason that is escaping me now. I believe it was I had no way of telling which had two sensors and which had one. I think you can drop the value from sensor 1 (213.2375). Not totally sure though. Happy to see a PR if have a good solution to this! Sorry I am not of more help or have time to debug this right now.

**Comment by chadhutchins182** [comment]
@mlucool Thanks for the reply!

I'll take the easy way out for now and drop [1] for now. I don't know enough about interacting with USB devices via node but I might try and learn!

**Comment by mlucool** [comment]
Seems there is nothing further here. Closing
